swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: PPA 2 Database Readout
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /bmi:
    get:
      operationId: "database.readBMI"
      tags:
        - "BMI"
      summary: "The bmi data record supported by the server application"
      description: "Retrieves the data stored for bmi function calls"
      responses:
        200:
          description: "Successful read bmi operation"
          schema:
            type: "array"
            items:
              properties:
                timestamp:
                  type: "string"
                feet:
                  type: "string"
                inches:
                  type: "string"
                pounds:
                  type: "string"
                classification:
                  type: "string"