swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: PPA 2 Database Readout
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /bmi:
    get:
      operationId: "database.readBMI"
      tags:
        - "BMI"
      summary: "The bmi data record supported by the server application"
      description: "Retrieves the data stored for bmi function calls"
      responses:
        200:
          description: "Successful read bmi operation"
          schema:
            type: "array"
            items:
              properties:
                timestamp:
                  type: "string"
                feet:
                  type: "string"
                inches:
                  type: "string"
                pounds:
                  type: "string"
                classification:
                  type: "string"
    post:
      operationId: "BMI.postBMI"
      tags:
        - "BMI"
      description: "Tries to call bmi function given the inputs"
      parameters:
        - name: feet
          in : query
          type: integer
          description: "The feet of the individual you'd like to calculate."
          required: true
        - name: inches
          in : query
          type: integer
          description: "The inches of the individual you'd like to calculate (as int)."
          required: true
        - name: pounds
          in : query
          type: number
          description: "The weight of the individual you'd like to calculate (as float)."
          required: true
      responses:
        201:
          description: "Posted"

  /email:
    get:
      operationId: "database.readEmailVerifier"
      tags:
        - "EmailVerifier"
      summary: "The email verification record supported by the server application"
      description: "Retrieves the data stored for email verifier function calls"
      responses:
        200:
          description: "Successful read email verifier operation"
          schema:
            type: "array"
            items:
              properties:
                timestamp:
                  type: "string"
                input:
                  type: "string"
                valid:
                  type: "string"
    post:
      operationId: "EmailVerifier.postEmailVerification"
      tags:
        - "EmailVerifier"
      description: "Tries to call Email Verifier function given the inputs"
      parameters:
        - name: email
          in : query
          type: string
          description: "The email you'd like to verify."
          required: true
      responses:
        201:
          description: "Posted"
